language: java

jdk:
  - oraclejdk8

script:
  - gradle ktlintCheck

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directoriies:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
